config/routes.rb
Bitlit::Application.routes.draw do
  root :to => "home#index"
  match "/login" => "user_sessions#new"
  match "/logout" => "user_sessions#destroy"

  resources :bits
  resources :comments
  resources :tags
  resources :user_sessions
  resources :users
  resource :account, :controller => "users"

end

app/models/bit.rb
class Bit < ActiveRecord::Base
  has_many :comments
  has_many :tags
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :bit
  belongs_to :comment, :foreign_key => "parent_id"
  has_many :comments, :foreign_key => "parent_id"
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :bit
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user_session, :current_user

  private
    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end

    def require_user
      unless current_user
        store_location
        flash[:notice] = "You must be logged in to access this page"
        redirect_to login_path
        return false
      end
    end

    def require_no_user
      if current_user
        store_location
        flash[:notice] = "You must be logged out to access this page"
        redirect_to account_url
        return false
      end
    end

    def store_location
      session[:return_to] = request.original_url
    end
    
    def redirect_back_or_default(default)
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end
end

app/controllers/bits_controller.rb
class BitsController < ApplicationController
  # GET /bits
  # GET /bits.json
  def index
    @bits = Bit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bits }
    end
  end

  # GET /bits/1
  # GET /bits/1.json
  def show
    @bit = Bit.find(params[:id])
    @new_comment = Comment.new
    @new_comment.bit = @bit

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bit }
    end
  end

  # GET /bits/new
  # GET /bits/new.json
  def new
    @bit = Bit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bit }
    end
  end

  # GET /bits/1/edit
  def edit
    @bit = Bit.find(params[:id])
  end

  # POST /bits
  # POST /bits.json
  def create
    @bit = Bit.new(params[:bit])

    respond_to do |format|
      if @bit.save
        format.html { redirect_to @bit, notice: 'Bit was successfully created.' }
        format.json { render json: @bit, status: :created, location: @bit }
      else
        format.html { render action: "new" }
        format.json { render json: @bit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bits/1
  # PUT /bits/1.json
  def update
    @bit = Bit.find(params[:id])

    respond_to do |format|
      if @bit.update_attributes(params[:bit])
        format.html { redirect_to @bit, notice: 'Bit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bits/1
  # DELETE /bits/1.json
  def destroy
    @bit = Bit.find(params[:id])
    @bit.destroy

    respond_to do |format|
      format.html { redirect_to bits_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(params[:comment])
    if @comment.save
      redirect_to @comment.bit, notice: 'Comment added.'
    else
      redirect_to @comment.bit, notice: 'Failed to add comment.'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    current_user
    @recent_bits = Bit.order("id DESC").limit(10)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
    tag = Tag.new(params[:tag])
    if tag.save
      redirect_to tag.bit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    bit_id = @tag.bit_id
    @tag.destroy

    redirect_to bit_path(bit_id)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:destroy]

  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_back_or_default account_url
    else
      render :action => :new
    end
  end
  
  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default new_user_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Account registered!"
      redirect_back_or_default account_url
    else
      render :action => :new
    end
  end
  
  def show
    @user = @current_user
  end

  def edit
    @user = @current_user
  end
  
  def update
    @user = @current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render :action => :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_path
    "/login"
  end
end

app/helpers/bits_helper.rb
module BitsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_path(params)
    "/comments"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bits/_form.html.erb
<%= form_for(@bit) do |f| %>
  <%= render :partial => "shared/errors", :object => @bit.errors %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bits/edit.html.erb
<h1>Editing bit</h1>

<%= render 'form' %>

<%= link_to 'Show', @bit %> |
<%= link_to 'Back', bits_path %>

app/views/bits/index.html.erb
<h1>Listing bits</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bits.each do |bit| %>
  <tr>
    <td><%= bit.title %></td>
    <td><%= bit.content %></td>
    <td><%= link_to 'Show', bit %></td>
    <td><%= link_to 'Edit', edit_bit_path(bit) %></td>
    <td><%= link_to 'Destroy', bit, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bit', new_bit_path %>

app/views/bits/new.html.erb
<h1>New bit</h1>

<%= render 'form' %>

<%= link_to 'Back', bits_path %>

app/views/bits/show.html.erb
<p id="notice"><%= notice %></p>

<p class="bit_title_container">
  <span class="bit_title"><%= @bit.title %></span>
</p>
<p class="bit_tags">
  <% @bit.tags.each do |tag| %>
    <span class="tag" onload="chooseTagColor(this)" ondblclick="removeTag(<%= tag.id %>)"><%= tag.name %></span>
  <% end %>
  <span class="add_tag"><a href="#" title="Add a tag" onclick="addTag(<%= @bit.id %>)">+</a></span>
</p>
<% @bit.tags.each do |tag| %>
  <form style="display: none; visibility: hidden;"
      action="<%= tag_path(tag.id) %>"
      method="post"
      id="delete_tag_<%= tag.id %>">
    <input type="hidden" name="_method" value="delete" />
  </form>
<% end %>

<p class="bit_content">
  <%= @bit.content.gsub(/\n/, "<br>").html_safe %>
</p>

<div class="comments">
<span class="comments_title">Comments</span><br>

<% @bit.comments.select { |x| x.parent_id.nil? }.each do |comment| %>
<%= render comment %>
<% end %>

<%= form_for(@new_comment) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :rows => 8 %>
  </div>
  <%= f.hidden_field :bit_id, :value => @bit.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>

<%= link_to 'Edit', edit_bit_path(@bit) %> |
<%= link_to 'Back', bits_path %>

app/views/comments/_comment.html.erb
<% this_width = if defined? width then width else 400 end %>

<div class="comment" id="comment<%= comment.id %>"
  style="width: <%= this_width %>px;">
<span class="comment_name"><%= comment.name %></span>
<p><%= comment.content.gsub(/\n/, "<br>").html_safe %></p>
<div class="comment_actions">
<a href="#comment<%= comment.id %>" onclick="reply(<%= comment.id.to_s + ',' + comment.bit_id.to_s %>)">reply</a>
| <%= link_to comment do %>permalink<% end %>
</div>
<div class="comment_replyspace"></div>
<% comment.comments.each do |child| %>
  <%= render :partial => "comments/comment", :locals => { :comment => child, :width => this_width - 20 }  %>
<% end %>
</div>

app/views/home/index.html.erb
<div style="float:right">
  <% if @current_user.nil? %>
    <%= link_to login_path do %>Login<% end %>
  <% else %>
    <%= link_to account_path do %><%= @current_user.login%><% end %>
  <% end %>
</div>
<p><%= link_to new_bit_path do %>Create a new bit<% end %></p>
<p><%= link_to bits_path do %>See all bits<% end %></p>
<p style="font-style: italic;">Showing recent Bits</p>
<div class="bit_list">
  <% @recent_bits.each do |bit| %>
    <div class="bit_list_item">
    <%= link_to bit_path(bit.id) do %>
      <span class="title"><%= bit.title %></span>
    <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BITLIT</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="logo">
  <%= link_to root_path do %>
    <%= image_tag "logo.png" %>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(errors.count, "error") %> prohibited this bit from being saved:</h2>

    <ul>
    <% errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= form_for(@user_session) do |f| %>
  <%= render :partial => "shared/errors", :object => @user_session.errors %>

  <%= f.label :login %><br />
  <%= f.text_field :login %><br />
  <br />
  <%= f.label :password %><br />
  <%= f.password_field :password %><br />
  <br />
  <%= f.check_box :remember_me %><%= f.label :remember_me %><br />
  <br />
  <%= f.submit "Login" %>
<% end %>

app/views/users/_form.html.erb
<%= form.label :login %><br />
<%= form.text_field :login %><br />
<br />
<%= form.label :password, form.object.new_record? ? nil : "Change password" %><br />
<%= form.password_field :password %><br />
<br />
<%= form.label :password_confirmation %><br />
<%= form.password_field :password_confirmation %><br />

app/views/users/edit.html.erb
<h1>Edit My Account</h1>

<% form_for @user, :url => account_path do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Update" %>
<% end %>

<br /><%= link_to "My Profile", account_path %>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_for @user, :url => account_path do |f| %>
  <%# f.error_messages %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Register" %>
<% end %>

app/views/users/show.html.erb
<p>
  <b>Login:</b>
  <%=h @user.login %>
</p>

<%= link_to 'Edit', edit_account_path %>